use crate::{
    dcap::{
        parser::{CursorExt, Parse, ParseError, ParseErrorExt},
        types::{EnclaveReport, TdxQuoteBody, TdxQuoteHeader},
    },
    parse_bail,
};

pub mod parser;
pub mod types;

#[derive(Debug)]
pub struct QeAuthenticationData<'a>(&'a [u8]);

impl QeAuthenticationData<'_> {
    pub fn inner(&self) -> &[u8] {
        self.0
    }
}

impl<'d> Parse<'d> for QeAuthenticationData<'d> {
    fn parse<'a>(mut cursor: impl parser::Cursor<'a>) -> Result<Self, ParseError>
    where
        'a: 'd,
    {
        let size: usize = cursor
            .take_u16()
            .context("could not read size of qe authentication data")?
            .into();

        cursor
            .split_off(size)
            .map(QeAuthenticationData)
            .context("not enough bytes to read Authentication Data")
    }
}

#[derive(Debug)]
pub struct QeReportCertificationData<'a> {
    pub qe_report: &'a EnclaveReport,
    pub qe_report_signature: &'a [u8; 64],
    pub qe_authentication_data: QeAuthenticationData<'a>,
    pub certification_data: QeCertificationData<'a>,
}

impl<'d> Parse<'d> for QeReportCertificationData<'d> {
    fn parse<'a>(mut cursor: impl parser::Cursor<'a>) -> Result<Self, ParseError>
    where
        'a: 'd,
    {
        let qe_report = cursor
            .zerocopy_ref::<EnclaveReport>()
            .context("failed parsing Enclave Report")?;

        let qe_report_signature = cursor
            .take_slice()
            .context("could not get QE Report Signature")?;

        let qe_authentication_data = cursor.parse()?;
        let certification_data = cursor.parse()?;

        Ok(Self {
            qe_report,
            qe_report_signature,
            qe_authentication_data,
            certification_data,
        })
    }
}

#[derive(Debug)]
pub enum QeCertificationData<'a> {
    PlainText(&'a [u8]),
    EncryptedCpuSvnsRSA2048(&'a [u8]),
    EncryptedCpuSvnsRSA3072(&'a [u8]),
    // PckLeaf, currently not supported
    PckChain(&'a [u8]),
    QeReportCertificationData(Box<QeReportCertificationData<'a>>),
    // PlatformManifest, currently not supported
}

impl QeCertificationData<'_> {
    const CPUSVNS: u16 = 0x01;
    const RSA2048: u16 = 0x02;
    const RSA3072: u16 = 0x03;
    const PCKCHAIN: u16 = 0x05;
    const QE_RCD: u16 = 0x06; // qe report certification data
}

impl<'d> Parse<'d> for QeCertificationData<'d> {
    fn parse<'a>(mut cursor: impl parser::Cursor<'a>) -> Result<Self, ParseError>
    where
        'a: 'd,
    {
        let certification_type = cursor
            .take_u16()
            .context("could not read certification type")?;

        let data_size = cursor
            .take_u32()
            .context("could not read cetification data size")?
            .try_into()
            .expect("integer did not fit in u32");

        let mut certification_data = cursor.split_off(data_size).context(format!(
            "not enough bytes {data_size} to parse certification_type = {certification_type}"
        ))?;

        // try to match all different qe certification data types
        let parsed = match certification_type {
            Self::CPUSVNS => Self::PlainText(certification_data),
            Self::RSA2048 => Self::EncryptedCpuSvnsRSA2048(certification_data),
            Self::RSA3072 => Self::EncryptedCpuSvnsRSA3072(certification_data),
            Self::PCKCHAIN => Self::PckChain(certification_data),
            Self::QE_RCD => Self::QeReportCertificationData(
                certification_data
                    .parse::<QeReportCertificationData>()?
                    .into(),
            ),
            _ => parse_bail!("unknown certification type in certification data"),
        };

        Ok(parsed)
    }
}

#[derive(Debug)]
pub struct Certification<'a> {
    /// ecdsa signature over the header and td quote body using the private part of attestation_key
    pub quote_signature: &'a [u8; 64],
    /// the public part of the attestation key generated by the quoting enclave
    pub attestation_key: &'a [u8; 64],
    /// data required to verify the signature over QE report and the attestation key
    pub quote_data: QeCertificationData<'a>,
}

impl<'d> Parse<'d> for Certification<'d> {
    fn parse<'a>(mut cursor: impl parser::Cursor<'a>) -> Result<Self, ParseError>
    where
        'a: 'd,
    {
        let quote_data_length: usize = cursor
            .take_u32()
            .context("could not get Quote Data length")?
            as usize;

        if quote_data_length > cursor.remaining() {
            parse_bail!("not enough data remaining to parse quote data")
        }

        let quote_signature = cursor
            .take_slice()
            .context("could not read quote signature")?;

        let attestation_key = cursor
            .take_slice()
            .context("could not read attestation key")?;

        let certification_data = cursor.parse::<QeCertificationData>()?;

        Ok(Self {
            quote_signature,
            attestation_key,
            quote_data: certification_data,
        })
    }
}

#[derive(Debug)]
pub struct TdQuote<'a> {
    pub quote_header: &'a TdxQuoteHeader,
    pub quote_body: &'a TdxQuoteBody,
    pub certification: Certification<'a>,
}

impl TdQuote<'_> {
    pub const TEE_TYPE_TDX: u32 = 0x81;
}

impl<'d> Parse<'d> for TdQuote<'d> {
    fn parse<'a>(mut cursor: impl parser::Cursor<'a>) -> Result<Self, ParseError>
    where
        'a: 'd,
    {
        let quote_header: &TdxQuoteHeader = cursor
            .zerocopy_ref()
            .context("failed to parse quote_header")?;

        // make some assumptions for attestation
        // - quote version == 4 (v3 is for SGX, v5 isn't out yet)
        // - tee_type is TDX
        // - attestation type is 2 (only one supported by tdx as per documentation)
        if quote_header.version != 4 {
            parse_bail!("Only v4 quotes are supported");
        }

        if quote_header.tee_type != Self::TEE_TYPE_TDX {
            parse_bail!("Only TDX is supported, not SGX");
        }

        if quote_header.attestation_type != 2 {
            parse_bail!("Attestation types other than 2 are not supported in TDX or SGX");
        }

        let quote_body = cursor
            .zerocopy_ref::<TdxQuoteBody>()
            .context("failed to parse quote_body")?;

        let certification = cursor.parse::<Certification>()?;

        Ok(TdQuote {
            quote_header,
            quote_body,
            certification, // certification_data: todo!(),
        })
    }
}
