on: ["push"]

jobs:
    clippy:
        name: Run cargo check/clippy on all targets
        strategy:
            matrix:
                package: ["nvidia-attest", "prem-rs", "snp-attest"]
                target: ["wasm32-unknown-unknown", "x86_64-unknown-linux-gnu"]
                exclude:
                    - package: prem-rs
                      target: x86_64-unknown-linux-gnu
                    - package: snp-attest
                      target: wasm32-unknown-unknown

                include:
                    - package: snp-attest
                      target: wasm32-unknown-unknown
                      features: snp-attest/kds_async
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: actions-rust-lang/setup-rust-toolchain@v1
              with:
                  target: ${{ matrix.target }}
            - name: Run Clippy
              run: cargo clippy --package=${{ matrix.package }} --target=${{ matrix.target }} --features="${{ matrix.features }}"
    test:
        needs: [clippy]
        name: Run unit tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - name: Run cargo test
              run: cargo test
    wasm:
        name: Run wasm-pack on prem-rs
        needs: [test]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - name: Install wasm-pack
              run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  registry-url: "https://npm.pkg.github.com/"
            - name: Run wasm-pack build
              run: wasm-pack build --scope ${{ github.repository_owner }} prem-rs
            - name: Add registry to package.json
              run: |
                  jq '. |= . + {"repository": {"type": "git", "url": "https://github.com/premAI-io/pcci-attestation-stack"}}' prem-rs/pkg/package.json
            - name: Publish npm package on the local github registry
              run: npm publish prem-rs/pkg/
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
