on: ["push"]

jobs:
    clippy:
        strategy:
            matrix:
                package: ["nvidia-attest", "prem-rs", "snp-attest"]
                target: ["wasm32-unknown-unknown", "x86_64-unknown-linux-gnu"]
                exclude:
                    - package: prem-rs
                      target: x86_64-unknown-linux-gnu
                include:
                    - package: snp-attest
                      features: snp-attest/kds_async
                    - package: snp-attest
                      features: snp-attest/kds_sync
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: actions-rust-lang/setup-rust-toolchain@v1
              with:
                  target: ${{ matrix.target }}
            - name: Run Clippy
              run: cargo clippy --package=${{ matrix.package }} --target=${{ matrix.target }} --features="${{ matrix.features }}"
